apiVersion: v1
kind: Service
metadata:
  name: flightlog-gateway-service
  namespace: flightlog
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 61225
      targetPort: 61225

