apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gateway
build:
  artifacts:
  - image: flightlog-gateway
    docker:
      dockerfile: Dockerfile-dev
deploy:
  kubectl:
    manifests:
    - gateway-service-configmap.yaml
    - gateway-service-deployment.yaml
    - gateway-service-service.yaml
