apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gateway
build:
  artifacts:
  - image: klyngen/flightlog-gateway
deploy:
  kubectl:
    manifests:
    - gateway-service-configmap.yaml
    - gateway-service-deployment.yaml
    - gateway-service-service.yaml
